# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-07 19:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MobileApp', '0002_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classcourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'classcourses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('courseid', models.AutoField(db_column='CourseID', primary_key=True, serialize=False)),
                ('coursecode', models.CharField(blank=True, db_column='CourseCode', max_length=50, null=True)),
                ('coursename', models.CharField(blank=True, db_column='CourseName', max_length=50, null=True)),
            ],
            options={
                'db_table': 'course',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('notificationid', models.AutoField(db_column='NotificationID', primary_key=True, serialize=False)),
                ('notificationdescription', models.TextField(db_column='NotificationDescription')),
                ('notificationdate', models.DateTimeField(db_column='NotificationDate')),
                ('isnotified', models.IntegerField(blank=True, db_column='IsNotified', null=True)),
            ],
            options={
                'db_table': 'notifications',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('sectionid', models.AutoField(db_column='SectionID', primary_key=True, serialize=False)),
                ('sectioncode', models.CharField(blank=True, db_column='SectionCode', max_length=20, null=True)),
                ('sectionname', models.CharField(blank=True, db_column='SectionName', max_length=50, null=True)),
            ],
            options={
                'db_table': 'section',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='class',
            table='class',
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('sectionid', models.ForeignKey(db_column='SectionID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='MobileApp.Section')),
                ('classid', models.ForeignKey(db_column='ClassID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, to='MobileApp.Class')),
                ('courseid', models.ForeignKey(db_column='CourseID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, to='MobileApp.Course')),
                ('agendadate', models.DateField(db_column='AgendaDate', primary_key=True)),
                ('agendadescription', models.TextField(db_column='AgendaDescription')),
                ('isquiz', models.IntegerField(blank=True, db_column='IsQuiz', null=True)),
            ],
            options={
                'db_table': 'agenda',
                'managed': False,
            },
        ),
    ]
